title: Stackbit Fresh Theme
baseURL: /
params:
  layout_style: overflow
  palette: blue
  header:
    title: Creative Craftsman
    tagline: Pradip Hudekar
    profile_img: images/pradip.jpg
    profile_img_alt: Author avatar
    background: dark
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Blog
        url: /blog/
        style: link
      - label: About
        url: /about/
        style: link
      - label: Contact
        url: /contact/
        style: link
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/hpradip'
        style: icon
        icon_class: twitter
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: instagram
        new_window: true
      - label: GitHub
        url: 'https://github.com/phudekar'
        style: icon
        icon_class: github
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/in/pradiphudekar'
        style: icon
        icon_class: linkedin
        new_window: true
      - label: DEV
        url: 'https://dev.to/'
        style: icon
        icon_class: dev
        new_window: true
  domain: 'https://creativecraftsman.in'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
